name: "Quarterly Report Update on the 1st of Each Month"
on:
  schedule:
    - cron: "0 1 1 * *"
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Runs script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If you're interested in analytics for a single repository without team breakdowns, GITHUB_TOKEN is sufficient.
          GITHUB_OWNER_FOR_ISSUE: "owner" # Make sure to specify the owner of the repository where the issue will be created
          GITHUB_REPO_FOR_ISSUE: "repo" # Make sure to specify the name of the repository where the issue will be created
          GITHUB_OWNERS_REPOS: "owner/repo" # Be sure to list the owner and repository name in the format owner/repo
          LABELS: "Report"
          CORE_HOURS_START: "8:00"
          CORE_HOURS_END: "20:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_PERIOD: "months:3"
          AGGREGATE_VALUE_METHODS: average
          PERIOD_SPLIT_UNIT: none
          ISSUE_TITLE: "Quarterly Report"
          TOP_LIST_AMOUNT: 5
          EXECUTION_OUTCOME: existing-issue
          ISSUE_NUMBER: 999 # Set issue number or change EXECUTION_OUTCOME to new-issue
