name: "Manual Execution for All Organization Repositories"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
      issue_title:
        description: "Issue title"
        required: false
      period_split_unit:
        description: "Unit for time segmentation"
        required: false
        default: "months"
        type: choice
        options:
          - years
          - quarters
          - months
          - none
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If you're interested in analytics for a single repository without team breakdowns, GITHUB_TOKEN is sufficient.
          GITHUB_OWNER_FOR_ISSUE: "owner" # Make sure to specify the owner of the repository where the issue will be created
          GITHUB_REPO_FOR_ISSUE: "repo" # Make sure to specify the name of the repository where the issue will be created
          LABELS: "Report"
          ORGANIZATIONS: "org-1"
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Europe/Berlin"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
          ISSUE_TITLE: ${{ inputs.issue_title }}
          PERIOD_SPLIT_UNIT: ${{ inputs.period_split_unit }}
